## Layers

In [4]:
# import packages
import sys
import os
from dotenv import load_dotenv
from IPython.display import display, HTML
import json
import matplotlib.pyplot as plt
import pandas as pd
import geopandas as gpd
from datetime import datetime
from urllib.parse import urlparse
from pathlib import Path

import rasterio
from rasterio.plot import show
import matplotlib.pyplot as plt
import pandas as pd


# Load environment variables from .env file
load_dotenv()

# import the API builder
from scoutmasterapi_builder.api import ScoutMasterAPI

In [ ]:
# Scoutmaster API - Credentials
client_id = os.getenv('SM_CLIENT_ID')
client_secret = os.getenv('SM_CLIENT_SECRET')
project_id = os.getenv('SM_PROJECT_ID')
dev = os.getenv("DEV")

# Scoutmaster API - Init
SM_API = ScoutMasterAPI(dev, version="v3")
SM_API.authenticate(client_id=client_id, client_secret=client_secret)

Initialized ScoutMaster API with host: https://dev-api.scoutmaster.nl/v3/
✅ Successfully authenticated ScoutMaster API
HOST: https://dev-api.scoutmaster.nl/v3/

In [9]:
df_fields = SM_API.fields(project_id)
df_fields

Empty DataFrame
Columns: []
Index: []

In [10]:
df_layer_types = SM_API.layer_types()
df_layer_types

Empty DataFrame
Columns: []
Index: []

In [ ]:
layer_type = df_layer_types.iloc[0]
layer_type_id = layer_type["id"]

field = df_fields.iloc[0]
field_id = field["id"]

In [7]:
print("FIELD:", field["name"], "ID:", field["id"])
print("LAYERTYPE:", layer_type["name"], "ID:", layer_type_id)

FIELD: Uiterwaarden 2,7 ha ID: 835be66e-97f3-4c7d-b72a-90e276215f61
LAYERTYPE: Prestatie ID: adbd41e6-6442-4ab7-961e-41e46556e118

In [ ]:
df_layers = SM_API.layers(field_id, layer_type_id)
df_layers 
# df_layers["updated_at"] = pd.to_datetime(df_layers["updated_at"], utc=True, errors="coerce")

# # Define 'today' in UTC
# today = pd.Timestamp(datetime.now().date()).tz_localize("UTC")

# # Filter rows where updated_at is today or later
# df_layers_today = df_layers[df_layers["updated_at"] >= today]
# df_layers_today

### plot vectors

In [9]:
dn_colors = {1: "#D1F2FF", 2: "#FF4700", 3: "#8ED547"}
for idx, row in df_layers.iterrows():
    file_path = row["path"]
    layer_type_name = row['layer_type']['name']
    parsed = urlparse(file_path)
    # Use the path part only
    extension = Path(parsed.path).suffix.lower().replace(".", "")
    if extension == "geojson":
        try:
            # Read GeoJSON
            gdf = gpd.read_file(file_path)
            
            # Optional: color by DN if the property exists
            if "DN" in gdf.columns:
                gdf["plot_color"] = gdf["DN"].map(dn_colors)
            else:
                gdf["plot_color"] = "#AAAAAA"  # fallback gray

            # Plot
            gdf.plot(color=gdf["plot_color"], edgecolor="black", alpha=0.7)
            plt.title(str(row.get("acquired_at", f"Layer {idx}")))
            plt.axis("equal")  # maintain aspect ratio
            plt.show()

        except Exception as e:
            print(f"⚠️ Failed to plot {file_path}: {e}")
    elif extension == "tif" or extension == "tiff":
        # Open the GeoTIFF directly from URL
        with rasterio.open(file_path) as src:
            print(src.nodata)
            fig, ax = plt.subplots(figsize=(8, 6))
            show(src, ax=ax, cmap='viridis')
            ax.set_title(f"Layer ID: {row['id']} - {layer_type_name}")
            plt.show()

NameError: name 'df_layers' is not defined