Projects

In [ ]:
# import packages
import sys
import os
from dotenv import load_dotenv
from IPython.display import display, HTML
import json
import matplotlib.pyplot as plt
import folium

# Load environment variables from .env file
load_dotenv()

# import the API builder
from scoutmasterapi_builder.api import ScoutMasterAPI

In [5]:
# Scoutmaster API - Credentials
client_id = os.getenv('SM_CLIENT_ID')
client_secret = os.getenv('SM_CLIENT_SECRET')
dev= os.getenv("DEV")

# Scoutmaster API - Init
SM_API = ScoutMasterAPI(dev, version="v3")
SM_API.authenticate(client_id=client_id, client_secret=client_secret)

Initialized ScoutMaster API with host: https://dev-api.scoutmaster.nl/v3/
✅ Successfully authenticated ScoutMaster API
HOST: https://dev-api.scoutmaster.nl/v3/

In [6]:
df_projects = SM_API.projects()
df_projects

,id,name,abbreviation,created_at,updated_at,logo_path
0,8574cc2c-857e-477d-8a7d-e14e047adb5e,,,2026-01-12T10:49:45.921Z,2026-01-12T10:49:45.921Z,NaN
1,6d3359ee-2988-4b23-b35b-14391e0eaa5f,04/06/2025 project,PR,2025-12-02T18:40:04.667Z,2026-02-18T15:09:20.289Z,https://bioscope-products-dev.s3.eu-central-1....
2,c52cc8b0-fd2e-4d7b-bc73-9623f8f212ae,Abaco project,AB,2025-12-02T18:40:04.667Z,2025-12-02T18:40:04.667Z,NaN
3,fafbd503-2a74-4162-9441-73473f320d32,bbbcccde,AA,2026-02-23T19:10:10.573Z,2026-03-09T11:49:26.987Z,https://bioscope-products-dev.s3.eu-central-1....
4,db21b65c-88b0-401f-b7e2-700737e1717a,ChicoGrow project,CH,2025-12-02T18:40:04.667Z,2026-03-06T12:25:00.817Z,https://bioscope-products-dev.s3.eu-central-1....
5,bb2fba1d-cea5-4359-9816-5d9f04bf1086,ddda,,2026-02-23T19:32:52.766Z,2026-03-06T17:17:02.292Z,https://bioscope-products-dev.s3.eu-central-1....
6,009d2bf9-8fe6-4da3-838c-6bef52a967ad,dddddddddde,DD,2026-02-23T19:35:12.173Z,2026-03-06T16:24:50.189Z,NaN
7,227ca66e-3108-4bd2-9b7e-8732c68e90ad,de,RE,2026-01-19T17:42:23.953Z,2026-03-06T16:24:59.424Z,NaN
8,7f80948c-4649-4d32-b185-b72ce538620b,dsds,,2026-02-23T19:32:08.885Z,2026-03-06T12:20:10.605Z,https://bioscope-products-dev.s3.eu-central-1....
9,ab3ace4e-5768-417f-a367-e53c88189659,Farmmaps,FA,2026-02-02T12:58:32.960Z,2026-02-18T15:11:06.910Z,https://bioscope-products-dev.s3.eu-central-1....
10,618658c0-a6e6-4325-bce5-ea5d211fdf84,hashtag,HA,2026-02-19T00:11:39.000Z,2026-02-19T00:11:39.000Z,NaN
11,ab056313-bcef-46ab-a804-d21f7186b943,hashtag,HA,2026-02-02T12:56:37.298Z,2026-02-02T12:56:37.298Z,NaN
12,d53ef9c9-9dfd-4410-b045-619dec1246c5,housee,HO,2026-02-23T20:04:26.206Z,2026-02-23T20:04:32.885Z,https://bioscope-products-dev.s3.eu-central-1....
13,282201d8-406a-46f3-91cf-9c5b4031556f,New Project,NP,2025-12-02T18:40:04.667Z,2025-12-02T18:40:04.667Z,NaN
14,7916f2f2-aa82-4daf-9db4-16b86386bbfd,sadsa,SA,2025-12-02T22:22:01.839Z,2025-12-02T22:22:01.839Z,NaN
15,48ba0c44-7c95-4fe2-8971-dd04ecfeda73,sadsdsadasda,SA,2025-12-02T22:22:43.602Z,2025-12-02T22:22:43.602Z,NaN
16,b3546dbd-0ad5-40cb-9f6f-b029522c6798,SoilZoning,SO,2026-03-16T11:55:59.887Z,2026-03-16T11:56:06.056Z,https://bioscope-products-dev.s3.eu-central-1....
17,ff9548db-3e82-4f59-9995-fdfb010ebb57,SQAT,Sq,2025-12-02T18:40:04.667Z,2025-12-02T18:40:04.667Z,NaN
18,2b49b4f1-b507-46d9-a2c7-da4ef8fd6b52,tes,TE,2026-03-11T17:59:40.776Z,2026-03-11T17:59:46.328Z,https://bioscope-products-dev.s3.eu-central-1....
19,a5834420-666b-4bb1-8337-fbb8f0a44d47,test,TE,2026-01-08T14:12:44.242Z,2026-01-08T14:12:44.242Z,NaN
20,a283dce3-2631-4a9e-be37-fbef710c2e88,test,Te,2025-12-02T18:40:04.667Z,2025-12-02T18:40:04.667Z,NaN
21,e27fa09b-4153-4d0f-8645-92c14aabaee1,test 3,Te3,2025-12-02T18:40:04.667Z,2025-12-02T18:40:04.667Z,NaN
22,2e797bed-0f43-4828-bf35-01a72272437b,test 3,TE,2026-02-02T23:51:27.877Z,2026-02-02T23:51:27.877Z,NaN
23,8b7edea6-7f0b-4680-b460-25be228bb30b,test 4,TE,2026-02-02T23:52:05.284Z,2026-02-02T23:52:05.284Z,NaN
24,295835dd-97e6-4f11-9681-a2e4a1e5da09,test5,TEST,2026-02-19T00:02:10.173Z,2026-02-19T00:02:10.173Z,NaN
25,aaec5e06-b0db-48e0-8faa-97c79ea755d0,test again,TE,2026-02-02T23:48:08.831Z,2026-02-02T23:48:08.831Z,NaN
26,5f88d0d3-e4fc-482d-8981-b3532fa7e2c7,Test Project,TE,2025-12-02T18:40:04.667Z,2025-12-02T18:40:04.667Z,https://bioscope-products-dev.s3.eu-central-1....
27,a6a6893f-ae3b-4221-a5a6-0144c70460b1,test sdsfsfsdfs 2,TE,2026-02-23T19:06:02.532Z,2026-03-06T12:30:58.373Z,https://bioscope-products-dev.s3.eu-central-1....
28,c3bbb430-b906-40ad-a431-1d58620beaaf,TOIS NEXT,TE,2026-02-23T19:06:02.532Z,2026-03-06T12:30:58.373Z,https://bioscope-products-dev.s3.eu-central-1....

In [7]:
# Create a new column for display
def display_logo_or_abbr(row):
    if row['logo_path']:
        return f'<img src="{row["logo_path"]}" width="200">'
    else:
        return f'<div style="font-weight:bold; font-size:14pt;">{row["abbreviation"]}</div>'

df_projects['display'] = df_projects.apply(display_logo_or_abbr, axis=1)

# Display table with HTML
display(HTML(df_projects[['id', 'name', 'display']].to_html(escape=False, index=False)))